[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

# --- IMPORTANT PERMISSIONS --- #

# write access to `vyper-storage` directory for storage layout overrides
fs_permissions = [{ access = "read-write", path = ".temp_vyper_storage.json" }]

# ffi access to run the vyper compiler
ffi = true
